process_pdf_task:
  description: >
    Extract text from the provided PDF content and add it to the RAG tool.
    Ensure the content is properly formatted and enriched for future queries.
  expected_output: >
    PDF content successfully added to the RAG tool.
  agent: pdf_processor

query_rag_task:
  description: >
    Formulate a query based on the user input and retrieve relevant information
    from the RAG tool. Ensure the results are accurate and well-organized.
  expected_output: >
    A detailed report containing the retrieved information, formatted as markdown.
  agent: query_agent